name: Build
on: [push]

jobs:
  job:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    env:
      # Indicates the CMake build directory where project files and binaries are being produced.
      CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir/
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg/

    steps:
      
      # Checkout the repo, including vcpkg submodule
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Setup the build agent machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
      - uses: lukka/get-cmake@latest
      
      # Install OS specific dependencies for some of our dependencies.
      # Currently, this is libusb on linux for hidapi.
      - name:  Install OS specific dependencies
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt-get -y install libudev-dev libusb-1.0-0-dev libfox-1.6-dev
            sudo apt-get -y install autotools-dev autoconf automake libtool
          fi
        shell: bash  
     
      # Restore both vcpkg and its artifacts from the GitHub cache service.
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v2
        with:
          # The first path is where vcpkg generates artifacts while consuming the vcpkg.json manifest file.
          # The second path is the location of vcpkg (it contains the vcpkg executable and data files).
          path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
            ${{ env.VCPKG_ROOT }}
          # The key is composed in a way that it get properly invalidated upon cache and trigger a new entry in the cache service.
          # The key includes: hash of the vcpkg.json file, the hash of the vcpkg Git commit id, and the used vcpkg's triplet. The vcpkg's commit id would suffice, but computing an hash out it does not harm.
          key: |
            ${{ hashFiles( 'vcpkg.json' ) }}-${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}-${{ matrix.triplet }}-v6
            
      # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly. As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
      - uses: ilammy/msvc-dev-cmd@v1
     
      # Run CMake to generate Ninja project files, using the vcpkg's toolchain file to resolve and install the dependencies as specified in vcpkg.json.
      - name: Install dependencies and generate project files
        run: |
          cmake -GNinja -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -D CMAKE_BUILD_TYPE=Release
      
      # Build the whole project with Ninja (which is spawn by CMake).
      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" --config Release

      - uses: actions/upload-artifact@v2
        with:
          name: spike-recorder.${{ matrix.os }}
          path: | 
            ${{ github.workspace }}/builddir/SpikeRecorder*
            ${{ github.workspace }}/builddir/*.dll
            ${{ github.workspace }}/builddir/*.so
            ${{ github.workspace }}/builddir/*.dylib
            ${{ github.workspace }}/builddir/*.plist
            ${{ github.workspace }}/builddir/*.entitlements
            ${{ github.workspace }}/builddir/data
            
            
            
            
